### ISSUE TITLE
Unexpected IllegalArgumentException

### ISSUE THREAD

**Issue by NTrubkin** [jlcout/epctagcoder#11]
I ran into a tag `urn:epc:id:sscc:4610052.9000000007`. I'm pretty sure the tag correct. But the following code fails:
```        
ParseSSCC.Builder()
         .withEPCPureIdentityURI("urn:epc:id:sscc:4610052.9000000007")
         .withTagSize(SSCCTagSize.BITS_96)
         .withFilterValue(SSCCFilterValue.RESERVED_5)
         .build();
```
```
java.lang.IllegalArgumentException: EPC Pure Identity is invalid
	at org.epctagcoder.parse.SSCC.ParseSSCC.parse(ParseSSCC.java:119)
	at org.epctagcoder.parse.SSCC.ParseSSCC.<init>(ParseSSCC.java:47)
	at org.epctagcoder.parse.SSCC.ParseSSCC.<init>(ParseSSCC.java:20)
	at org.epctagcoder.parse.SSCC.ParseSSCC$Steps.build(ParseSSCC.java:266)
...
```

**Comment by jlcout** [comment]
Hi Trubkin!

New version 0.0.8 is available. I found a small error in a regular expression and it was fixed.

Thanks for reporting.

Здоровья тебе и твоей семье. Привет из Brazil

**Comment by NTrubkin** [comment]
You are awesome. Thank you.
